---

- name: Configure SSH access
  hosts: all
  become: yes

  tasks:

  - name: Update APT package cache
    apt: update_cache=yes

  - name: Add non-root user
    user: name=homelab state=present shell=/bin/bash

  - name: Set up authorized key for user
    authorized_key: user=homelab state=present key="{{lookup('file', '/home/adam/Desktop/projects/homelab/ansible/homelab.pub')}}"

  - name: Remove sudo group rights
    action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

  - name: Add user to sudoers
    action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="homelab ALL=(ALL) NOPASSWD:ALL" state=present

  - name: Disallow root SSH access
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

  - name: Disallow password authentication
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart ssh

  handlers:

  - name: Restart ssh
    action: service name=ssh state=restarted
