---

- name: Configure the Pihole
  hosts: pihole
  become: yes

  tasks:

  - name: Ensure prometheus user exists
    user:
      name: prometheus
      shell: /bin/false

  - name: Download Node exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-armv7.tar.gz
      dest: /tmp
      checksum: sha256:e7f4427a25f1870103588e4968c7dc8c1426c00a0c029d0183a9a7afdd61357b

  - name: Create Node exporter folder in /usr/bin
    become: yes
    file:
      path: /usr/bin/nodeexporter
      state: directory
      owner: prometheus
      group: prometheus
      mode: '0777'

  - name: Extract Node exporter
    become: yes
    unarchive:
       src: /tmp/node_exporter-1.0.1.linux-armv7.tar.gz
       dest: /usr/bin/nodeexporter
       remote_src: yes

  - name: Copy Node exporter Service File from local machine
    copy:
        src: node_exporter/nodeexporter.service
        dest: /etc/systemd/system/nodeexporter.service

  - name: systemd reload
    become: yes
    systemd:
      daemon_reload: yes

  - name: Start Node exporter service
    become: yes
    service:
      name: nodeexporter
      enabled: yes
      state: started

  handlers:

  - name: Restart ssh
    action: service name=ssh state=restarted
